# Emit detailed paths for the core system clock. The SDRAM clock is no longer
# generated by this core PLL, so querying it only produces an empty-clock
# warning and stale reports from older builds.
set core_sys_clock [get_clocks {*emu|pll|pll_inst|altera_pll_i|general[1].gpll~PLL_OUTPUT_COUNTER|divclk}]

report_timing -setup -to_clock $core_sys_clock -npaths 10 \
	-detail full_path -show_routing \
	-file output_files/GundamEX.sys_setup_paths.txt
